# POST http://localhost:5000/api/nilai
# content-type: application/json

# {
#     "nik" : "171751",
#     "periode" : "periode1",
#     "kelas" : 2
# }

# POST http://localhost:5000/api/report/get
# content-type: application/json

# {
#     "kode_divisi" : "405",
#     "periode" : "periode1",
#     "kelas" : 1
# }

# GET  http://localhost:5000/api/kamus/get


POST http://localhost:5000/api/divisi
content-type: application/json

{
    "kelas" : 2,
    "divisi" : 405
}